# irirs of px4_sitl
# measurement noise IMU in its own frame
RImu:
    Omega:  {x: 3.0e-6, y: 3.0e-6, z: 3.0e-6}
    a:      {x: 4.84e-2, y: 4.84e-2, z: 4.84e-2}

# process model uncertainty
Qx: [7.5e-7, 7.5e-7, 7.5e-7,    # q
     1.0e-7, 1.0e-7, 1.0e-7,    # r
     1.0e-5, 1.0e-5, 1.0e-5,    # v
     7.5e-5, 7.5e-5, 7.5e-5,    # Omega
     2.50e-7,                   # m
     5.0e-11, 5.0e-11, 5.0e-11, # I
     4.0e-8, 4.0e-8, 4.0e-8,    # r_BM
     4.0e-8, 4.0e-8, 4.0e-8,    # r_BP
     4.0e-8, 4.0e-8,            # r_BI
     1.0e-4, 1.0e-4, 1.0e-4,    # b_a
     1.0e-6, 1.0e-6, 1.0e-6]    # b_Omega

# initialization state variables
x0:
    m:    1.369
    I:    {x: 0.023, y: 0.023, z: 0.023}
    r_BM: {x: 0.0, y: 0.0, z: 0.0}
    r_BP: {x: 0.0, y: 0.0, z: 0.0}
    r_BI: {x: 0.0, y: 0.0}
    # m:    0.2463
    # I:    {x: 0.623e-3, y: 0.678e-3, z: 1.076e-3}
    # r_BM: {x: 3.0e-3, y: -0.5e-3, z: 25.0e-3}
    # r_BP: {x: 42.42e-3, y: 16.38e-3, z: 0.0e-3}
    # r_BI: {x: 42.42e-3, y: 16.38e-3}

# initialization state covariance
P0:
    v:       {x: 5.0, y: 5.0, z: 5.0} #{x: 1.0e-2, y: 1.0e-2, z: 1.0e-2} #
    m:       6.0e-2
    I:       {x: 3.9e-7, y: 3.9e-7, z: 3.9e-7}
    r_BM:    {x: 2.5e-3, y: 2.5e-3, z: 2.5e-3}
    r_BP:    {x: 2.5e-3, y: 2.5e-3, z: 2.5e-3}
    r_BI:    {x: 2.5e-3, y: 2.5e-3}
    b_a:     {x: 4.0, y: 4.0, z: 4.0}
    b_Omega: {x: 1.0, y: 1.0, z: 1.0}

# UKF tuning parameters
UKF:
    alpha: 1 
    beta:  2.0
    kappa: 0.0

# attitude pose sensor - 3x3 rotation matrix (row major)
R_BP: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

# attitude IMU - 3x3 rotation matrix (row major)
R_BI: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
# order have to be change for px4
multirotor:
    rotor1: # have only as many "rotor(i)" as there are on the multirotor
        kf: 5.84e-06
        km: 3.5040e-07  #  c=km/kf=
        R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
        t: [ 0.13, 0.22, 0.023]  #[l, w, 0]
    rotor2:
        kf: 5.84e-06
        km: -3.5040e-07
        R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
        t: [ -0.13, 0.22, 0.023]
    rotor3:
        kf: 5.84e-06
        km: 3.5040e-07
        R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
        t: [ -0.13, -0.22, 0.023]
    rotor4:
        kf: 5.84e-06 # motorConstant/(30/pi)^2=kf,//  but usrad/s here since noise is important
        km: -3.5040e-07 # # momentConstant*kf=km - negative if counter-clockwise0,  positive if clockwise
        R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] # rotor attitude - row major matrix
        t: [ 0.13, -0.22, 0.023] # rotor position
